on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build_vsix:
    name: Build extension
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install -g @vscode/vsce

    - name: Build extension
      run: |
        mkdir vsix
        extension_file="vsix/cottle-vscode-$(git rev-parse --short HEAD).vsix"
        echo "filename=$extension_file" >> $GITHUB_ENV
        vsce package --out $extension_file

    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: cottle-vscode-extension
        path: $extension_file
